version: '3'

services:
    de4aconnector:
        image: de4a/connector:latest
        ports:
            - "8080:8080"
        volumes:
            - ./config/application.properties:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/application.properties
            - ./config/de-do.json:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/de-do.json
# TODO add keystore
#            - ./config/keystore.p12:/de4a/keystore.p12
            - /tmp/connector:/tmp
