addresses:
    dataOwners:
        iso6523-actorid-upis::9999:ess2833002e-it2: https://pre-smp-dr-de4a.redsara.es/de4a-it2-mock-connector/
        iso6523-actorid-upis::9999:at000000271-it2: https://pre-smp-dr-de4a.redsara.es/de4a-it2-mock-connector/
        iso6523-actorid-upis::9999:nl990000106-it2: https://pre-smp-dr-de4a.redsara.es/de4a-it2-mock-connector/
        iso6523-actorid-upis::9999:se000000013-it2: https://pre-smp-dr-de4a.redsara.es/de4a-it2-mock-connector/
        iso6523-actorid-upis::9999:ro000000006-it2: https://pre-smp-dr-de4a.redsara.es/de4a-it2-mock-connector/
        iso6523-actorid-upis::9999:nl000000024-it2: https://pre-smp-dr-de4a.redsara.es/de4a-it2-mock-connector/
        iso6523-actorid-upis::9999:si000000016-it2: https://pre-smp-dr-de4a.redsara.es/de4a-it2-mock-connector/
        iso6523-actorid-upis::9999:pt990000101-it2: https://pre-smp-dr-de4a.redsara.es/de4a-it2-mock-connector/
        iso6523-actorid-upis::9999:pt000000026-it2: https://pre-smp-dr-de4a.redsara.es/de4a-it2-mock-connector/
        iso6523-actorid-upis::9920:ess2833002e-it2: https://pre-smp-dr-de4a.redsara.es/de4a-it2-mock-connector/
        iso6523-actorid-upis::9991:at000000271-it2: https://pre-smp-dr-de4a.redsara.es/de4a-it2-mock-connector/
        iso6523-actorid-upis::9991:nl990000106-it2: https://pre-smp-dr-de4a.redsara.es/de4a-it2-mock-connector/
        iso6523-actorid-upis::9991:se000000013-it2: https://pre-smp-dr-de4a.redsara.es/de4a-it2-mock-connector/
        iso6523-actorid-upis::9991:ro000000006-it2: https://pre-smp-dr-de4a.redsara.es/de4a-it2-mock-connector/
        iso6523-actorid-upis::9991:nl000000024-it2: https://pre-smp-dr-de4a.redsara.es/de4a-it2-mock-connector/
        iso6523-actorid-upis::9991:si000000016-it2: https://pre-smp-dr-de4a.redsara.es/de4a-it2-mock-connector/
        iso6523-actorid-upis::9991:pt990000101-it2: https://pre-smp-dr-de4a.redsara.es/de4a-it2-mock-connector/
        iso6523-actorid-upis::9991:pt000000026-it2: https://pre-smp-dr-de4a.redsara.es/de4a-it2-mock-connector/
    dataEvaluators:
        iso6523-actorid-upis::9999:ess2833002e-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9999:at000000271-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9999:nl990000106-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9999:se000000013-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9999:ro000000006-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9999:nl000000024-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9999:si000000016-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9999:si000000018-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9999:pt990000101-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9999:esq6250003h-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9999:lu000000025-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9920:ess2833002e-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9991:at000000271-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9991:nl990000106-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9991:se000000013-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9991:ro000000006-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9991:nl000000024-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9991:si000000016-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9991:si000000018-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/
        iso6523-actorid-upis::9991:pt990000101-it1: https://de4a-portal.gsd.inesc-id.pt:8443/api/de/
        iso6523-actorid-upis::9920:esq6250003h-it1: https://ujiapps.uji.es/sdg/rest/services/
        iso6523-actorid-upis::9991:lu000000025-it1: https://de4a-demoui.informatika.uni-mb.si/de1/usi/